name: auto-approve-and-merge

on:
  pull_request:
    branches:
      - 'master'

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  statuses: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Approve a PR
        if: github.actor == 'APPROVEDUSER'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  auto-merge:
    needs: auto-approve
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      
      
