name: auto-approve-and-merge

on:
  pull_request:
    branches:
      - 'master'

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  statuses: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Approve a PR
        if: github.actor == 'APPROVEDUSER'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  auto-merge:
    needs: auto-approve
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        if: github.actor == 'APPROVEDUSER'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            console.log('Merged 🎉');
